// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon.png
var resourceIconPngData []byte
var ResourceIconPng = &fyne.StaticResource{
	StaticName:    "assets/icon.png",
	StaticContent: resourceIconPngData,
}
